### ISSUE TITLE
cant close 

### ISSUE THREAD

**Issue by sanyashvets** [joearcher/vue-droppler#4]
install such like this
```
<droppler class="hidden-lg" position="bottom left" openOn="click" constrainToWindow="true">
					<button slot="drop-trigger">test</button>
					<mail-sidebar slot="drop-content"></mail-sidebar>
				</droppler>
```
and cant close. It fires events, classes changed, but content doesnt disappear

**Comment by sanyashvets** [comment]
I can make it with adding some extra styles, but is there a right way ?

**Comment by joearcher** [comment]
Adding your own styles is the correct way to do this.
